# -*- coding: utf-8 -*-
"""Vignesh -  STA2453-Lab-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15utDlC7SfBDfVDrzaT2Qj2yGpN_9r2Z_
"""

# Let's code it up, preamble first. 

import numpy as np # basic vector/matrix math
import matplotlib.pyplot as plt # plotting and illustrations 
import seaborn as sns # advanced plotting and illustrations. 
import pandas as pd # data loading, saving, and general data manipulation. 
import scipy.stats as stats # inter alia, statistical distributions, functions and relevant objects.
import scipy.optimize as optimize 
import torch # ML/AI model's and general optimization

"""# STA 2453 Lab 1 Submission

This lab notebook must be completed in the appropriate time during class and invigilated by the instructor. There are _ questions, you must add both this notebook, and another generated .py file to the PR. 

Once the PR is in place, please tag both me and the TA in it. So in the end you will have two files. 

- `STA2453-Lab-1.ipynb`
- `STA2453-Lab-1.py`

Both of these are needed for a good submission.

# Case Study: Does God Hate Rich People? 


## Introduction 

Extreme weather events in the U.S. are regularly tracked by the National Oceanic and Atomspheric Administration (NOAA).

The NCDC Storm Events database is provided by the National Weather Service (NWS) and contain statistics on personal injuries and damage estimates. (ref. gov.noaa.ncdc:C00510). 

## The question is, are high-income or low-income households more susceptible to extreme weather events? 

The US Household Income dataset provided by Golden Oak Research Group contains 32,000 records on US Household Income Statistics & Geo Locations. The dataset originally developed for real estate and business investment research. Income is a vital element when determining both quality and socioeconomic features of a given geographic location. (ref. Golden Oak Research Group, LLC. “U.S. Income Database Kaggle”. Publication: 5, August 2017.)


The two files listed here: 

## Storm Weather Event Data
`https://raw.githubusercontent.com/nikpocuca/sta2453-2022.github.io/master/StormEvents_locations-ftp_v1.0_d2014_c20180718.csv`


## Golden Oak Research Group Data
`https://raw.githubusercontent.com/nikpocuca/sta2453-2022.github.io/master/kaggle_income_clean.csv`
"""

# Load data
storm_data = pd.read_csv("https://raw.githubusercontent.com/nikpocuca/sta2453-2022.github.io/master/StormEvents_locations-ftp_v1.0_d2014_c20180718.csv")
golden_data = pd.read_csv("https://raw.githubusercontent.com/nikpocuca/sta2453-2022.github.io/master/kaggle_income_clean.csv")

storm_data.info()

golden_data.info()

golden_data.sample(1)

"""
## Cleaning Data 

We want to take only the continental US data, so that involves the following: 

- `20 < Lat < 50`
- `Lon > -140`


Furthermore we want to create two dataframes, one for poor people, one for rich people. According to the US Census Bureau, a person who's average income is below \$25k is considered below the poverty line, while a person exceeding \$100k is considered wealthy. 

Create two dataframes called `rich_df` and `poor_df` for analysis after cleaning out for strictly continental US. 
"""

# clean df. 
clean_storm_df = storm_data[(storm_data.LATITUDE > 20.0) & (storm_data.LATITUDE < 50.0) & (storm_data.LONGITUDE > -140.0)]

clean_golden_data = golden_data[(golden_data.Lat > 20.0) & (golden_data.Lat < 50.0) & (golden_data.Lon > -140.0)]

# rich/poor segmentation
poor_df = clean_golden_data[clean_golden_data.Mean < 25000]
rich_df = clean_golden_data[clean_golden_data.Mean > 100000]

poor_df.shape

rich_df.shape

"""## Calculate Nearest Distance between Points

For each household we need to calculate the nearest severe weather event. We should write a function to do this. Let $x$,$y$ denote longitude and latitude respectively. then for some Houshold $H$, we should calculate the distance to all the severe weather events $E$ longitude and latitude. 


$$ d_{H,E} = 110.574 \times \sqrt{(x_H - x_E)^2 + (y_H - y_E)^2} $$

Basically we are getting a eucledian distance to each severe weather event, and then multiplying by a constant to convert to km's for sanity. Then we want to find the distance to the nearest event so we take the minimum... 

$$ d_{min} = \text{argmin}\{d_{H,E_1}, d_{H,E_2}, \dots, d_{H,E_n} \} $$ 


Do this for every household, and plot the results in a histogram for both rich/poor households.  
"""

# calculate the nearest points.
def calc_min_distance(golden_item):
  return np.min(110.574 * np.sqrt((clean_storm_df.LONGITUDE - golden_item.Lon) ** 2 + (clean_storm_df.LATITUDE - golden_item.Lat) ** 2))

rich_df["min_storm_distance"] = rich_df.apply(calc_min_distance, axis=1).to_numpy()

poor_df["min_storm_distance"] = poor_df.apply(calc_min_distance, axis=1).to_numpy()

X_rich = rich_df.min_storm_distance.to_numpy()
X_poor = poor_df.min_storm_distance.to_numpy()

# plot rich people histogram, make bins at least 50, comment on the plot.
plt.hist(X_rich, bins=50)

# plot poor people histogram, make bins at least 50, comment on the plot
plt.hist(X_poor, bins=50)

"""# Distributional Characteristic Statistics

In the following cells please perform some statistical analysis and determine whether rich people are more likely to be struck by extreme weather events, or, poor people are more likely. The methods/statistics presented in week one in class are extremely useful.  

You should also find the difference of mean pooled t-test useful in this case but you must justify your assumptions for using it. You can use any python libraries or functions as well as go on stack overflow. You should also use the functions written up in the previous class [here](https://colab.research.google.com/drive/1L1Kx8qoHCY3yjuYg2tE4W61xu79xG7lJ?usp=sharing).

$$ t = \frac{ \bar{X}_R - \bar{X}_P}{ s_T \sqrt{\frac{1}{n_R} + \frac{1}{n_P}}  } $$

where, 
$$ s_T = \sqrt{ \frac{(n_R - 1)s_R + (n_P -1)s_P}{n_R + n_P - 2}  }  $$

Hint: Use the following function `stats.ttest_ind` and adjust the appropriate setting such that you test wether $\bar{X}_R > \bar{X}_P$, or vice versa.

Hint-2: Use the functions from the previous week's notebook. 

Caveat: Keep resampling techniques under 500 scenarios (in class we used 1000).


### Please write your conclusion at the end wether Rich or Poor people are more likely to get hit by a severe weather storm.

From the histogram we can see that both X_rich and X_poor have similar distribution.

If we assume mean(x_rich) = mean(X_poor), then we can use the permutation re-sampling method to compute the T statistic
"""

# Null hypothesis = mean(X_rich) = mean(X_poor)
# Alternate hypothesis = mean(X_rich) > mean(X_poor)
stats.ttest_ind(X_rich, X_poor, alternative="greater")

"""Accept null *hypothesis*"""

# Null hypothesis = mean(X_rich) = mean(X_poor)
# Alternate hypothesis = mean(X_rich) < mean(X_poor)
stats.ttest_ind(X_rich, X_poor, alternative="less", permutations=500, equal_var=False)

"""Reject null hypothesis and accept alternate hypothesis mean(X_rich) < mean(X_poor)

### Conclusion: Since rich people are nearer to storms, they are more likely to get hit
"""